version: '3.7'
services:
  robert2web:
    image: maximelaplanche/robert2:latest
    networks:
      - robert2_db_network
      - robert2_network
      - frontend
    depends_on:
      - robert2db
    links:
      - robert2db:robert2db
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.robert2.tls.certresolver=myresolver
      - traefik.http.routers.robert2.rule=Host(`${URI_DOMAIN}`)
      - traefik.http.routers.robert2.entrypoints=entrypoints-https
#      - traefik.http.services.robert2.loadbalancer.server.port=8080

  robert2db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./robert2_data:/var/lib/mysql
    networks:
      - robert2_db_network

networks:
  frontend:
    external: true
  robert2_network:
    name: "robert2_network"
  robert2_db_network:
    name: "robert2_db_network"
